version: "3.9"

services:
  web:
    container_name: web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/setup && rails s -b 0.0.0.0"
    volumes:
      - .:/my_expenses_app
      - rubygems:/usr/local/bundle
    ports:
      - 3000:3000
    networks:
      - my_expenses
    depends_on:
      database_development:
        condition: service_started

  database_development:
    container_name: database_development
    image: postgres:15-alpine
    volumes:
      - database_development:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: my_expenses_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - my_expenses

  database_test:
    container_name: database_test
    image: postgres:15-alpine
    volumes:
      - database_test:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: my_expenses_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - my_expenses

networks:
  my_expenses:

volumes:
  database_development:
  database_test:
  rubygems:
