default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: my_expreses_development

test:
  <<: *default
  database: my_expreses_test

production:
  <<: *default
  database: my_expreses_production
  username: my_expreses
  password: <%= ENV['MY_EXPRESES_DATABASE_PASSWORD'] %>
