default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password

development:
  <<: *default
  host: database_development
  database: my_expenses_development

test:
  <<: *default
  host: database_test
  database: my_expenses_test

production:
  <<: *default
  host: database_production
  database: my_expenses_production
  username: my_expenses_user
  password: <%= ENV['MY_EXPENSES_DATABASE_PASSWORD'] %>
