# Generated by Django 5.1 on 2024-09-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_remove_expense_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
